export const data = [
    {   
        id:"FR26412",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/HLC_New_logo_Products__FREEZE_TRA_XANH.png",
        name: "FREEZE",
        subname:"trà xanh",
        vote: 4.5,
        price: 10,
        description: "Thức uống rất được ưa chuộng! Trà xanh thượng hạng từ cao nguyên Việt Nam, kết hợp cùng đá xay, thạch trà dai dai, thơm ngon và một lớp kem dày phủ lên trên vô cùng hấp dẫn. Freeze Trà Xanh thơm ngon, mát lạnh, chinh phục bất cứ ai!",
        category: "FREEZE",
        popular: true,
        bestSeller: false,
        sale:false,
    },
    {   
        id:"FR26320",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/HLC__COOKIES_n_CREAM.jpg",
        name: "FREEZE",
        subname:"cookies & cream",
        vote: 4,
        price: 5.5,
        description: "Một thức uống ngon lạ miệng bởi sự kết hợp hoàn hảo giữa cookies sô cô la giòn xốp cùng hỗn hợp sữa tươi cùng sữa đặc đem say với đá viên, và cuối cùng không thể thiếu được chính là lớp kem whip mềm mịn cùng cookies sô cô la say nhuyễn.",
        category: "FREEZE",
        popular: true,
        bestSeller: false,
        sale:false,
    },
    {   
        id:"FR25302",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/HLC__FREEZE_SO-CO-LA.jpg",
        name: "FREEZE",
        subname:"chocolate",
        vote: 5,
        price: 15,
        description: "Thiên đường đá xay sô cô la! Từ những thanh sô cô la Việt Nam chất lượng được đem xay với đá cho đến khi mềm mịn, sau đó thêm vào thạch sô cô la dai giòn, ở trên được phủ một lớp kem whip beo béo và sốt sô cô la ngọt ngào. Tạo thành Freeze Sô-cô-la ngon mê mẩn chinh phục bất kì ai!",
        category: "FREEZE",
        popular: false,
        bestSeller: true,
        sale:false,
    },
    {   
        id:"CF15260",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/HLC__PHINDI_CHOCO.jpg",
        name: "COFFEE",
        subname:"phindi choco",
        vote: 3,
        price: 4,
        description: "PhinDi Choco - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Choco ngọt tan mang đến hương vị mới lạ, không thể hấp dẫn hơn!",
        category: "COFFEE",
        popular: true,
        bestSeller: true,
        sale:false,
    },
    {   
        id:"CF24200",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/HLC__PHINDI_KEM_SUA.jpg",
        name: "COFFEE",
        subname:"PHINDI CREAM MILK",
        vote: 4.5,
        price: 12,
        description: "PhinDi Kem Sữa - Cà phê Phin thế hệ mới với chất Phin êm hơn, kết hợp cùng Kem Sữa béo ngậy mang đến hương vị mới lạ, không thể hấp dẫn hơn!",
        category: "COFFEE",
        popular: true,
        bestSeller: false,
        sale:false,
    },
    {   
        id:"CF21500",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/HLC__BAC_XIU_DA.jpg",
        name: "COFFEE",
        subname:"RED COINS",
        vote: 5,
        price: 18,
        description: "Nếu Phin Sữa Đá dành cho các bạn đam mê vị đậm đà, thì Bạc Xỉu Đá là một sự lựa chọn nhẹ 'đô' cà phê nhưng vẫn thơm ngon, chất lừ không kém!",
        category: "COFFEE",
        popular: false,
        bestSeller: true,
        sale:false,
    },
    {   
        id:"TE30412",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/HLC__TRA_THANH_DAO-08.jpg",
        name: "TEA",
        subname:"TRÀ THANH ĐÀO",
        vote: 3.5,
        price: 8,
        description: "Một trải nghiệm thú vị khác! Sự hài hòa giữa vị trà cao cấp, vị sả thanh mát và những miếng đào thơm ngon mọng nước sẽ mang đến cho bạn một thức uống tuyệt vời.",
        category: "TEA",
        popular: true,
        bestSeller: false,
        sale:true,
        priceSale:5
    },
    {   
        id:"TE30412",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/Tra_Xoai.jpg",
        name: "TEA",
        subname:"TRÀ XOÀI NHIỆT ĐỚI",
        vote: 4.5,
        price: 8,
        description: "Với vị ngọt thanh, chua nhẹ đặc trưng của trái xoài nhiệt đới hài hòa cùng vị trà cao cấp và những viên thạch ngọc trai giòn dai nhai vui miệng sẽ mang đến cho bạn một thức uống đánh bay cái nóng mùa hè!",
        category: "TEA",
        popular: false,
        bestSeller: false,
        sale:true,
        priceSale:9
    },
    {   
        id:"TE30000",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/11_2022/BR_Drink/New_HC_Product_Tra_Oi_Hong.png",
        name: "TEA",
        subname:"TRÀ ỔI HỒNG",
        vote:5,
        price: 7,
        description: "Sự kết hợp thú vị giữa chất thanh mát từ trà xanh lài cùng hương thơm nhẹ nhàng và vị chua ngọt của ổi hồng sẽ mang tới một trải nghiệm tuyệt vời!",
        category: "TEA",
        popular: false,
        bestSeller: false,
        sale:false,
    },
    {   
        id:"CA26510",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/03_2018/MOUSSECACAO.png",
        name: "CAKE",
        subname:"MOUSSE CACAO",
        vote: 3,
        price: 15,
        description: "Bánh Mousse Ca Cao, là sự kết hợp giữa ca-cao Việt Nam đậm đà cùng kem tươi.",
        category: "CAKE",
        popular: true,
        bestSeller: true,
        sale:false,
    },
    {   
        id:"CA36411",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/03_2018/PHOMAICAPHE.jpg",
        name: "CAKE",
        subname:"PHÔ MAI CÀ PHÊ",
        vote: 4.5,
        price: 18,
        description: "Làm từ cà phê truyền thống của Highlands, kết hợp với phô mai thơm ngon! Chiếc bánh phù hợp đi cùng với bất cứ món cà phê nào!",
        category: "CAKE",
        popular: true,
        bestSeller: false,
        sale:false,
    },
    {   
        id:"CA40512",
        url: "https://www.highlandscoffee.com.vn/vnt_upload/product/03_2018/CARAMELPHOMAI.jpg",
        name: "CAKE",
        subname:"CARAMEL PHÔ MAI",
        vote: 5,
        price: 20,
        description: "Ngon khó cưỡng! Bánh phô mai thơm béo được phủ bằng lớp caramel ngọt ngào.",
        category: "CAKE",
        popular: true,
        bestSeller: false,
        sale:true,
        priceSale:10
    },
]